export const DOM = {
    overlayImage: document.getElementById('overlay-image'),
    battingTeamLogo: document.getElementById('batting-team-logo'),
    bowlingTeamLogo: document.getElementById('bowling-team-logo'),
    batsman1Name: document.getElementById('batsman1-name'),
    batsman1RunsBalls: document.getElementById('batsman1-runs-balls'),
    batsman2Name: document.getElementById('batsman2-name'),
    batsman2RunsBalls: document.getElementById('batsman2-runs-balls'),
    bowlerName: document.getElementById('bowler-name'),
    bowlerFigures: document.getElementById('bowler-figures'),
    bowlerWicketsRuns: document.getElementById('bowler-wickets-runs'),
    bowlerOvers: document.getElementById('bowler-overs'),
    teamName: document.getElementById('team-name'),
    teamScore: document.getElementById('team-score'),
    teamWickets: document.getElementById('team-wickets'),
    teamOvers: document.getElementById('team-overs'),
    secondInnings: document.getElementById('secondInnings'),
    result: document.getElementById('result'),
    matchResult: document.getElementById('match-result'),
    secondTeamName: document.getElementById('second-team-name'),
    secondTeamScore: document.getElementById('second-team-score'),
    secondTeamWickets: document.getElementById('second-team-wickets'),
    secondTeamOvers: document.getElementById('second-team-overs'),
    scoreNeeded: document.getElementById('score-needed'),
    ballContainer: document.getElementById('ball-by-ball'),
    batsmanInfo: document.getElementById('batsman-info'),
    bowlerInfo: document.getElementById('bowler-info'),
};
