export const mock_toss = {
    "view": 1,
    "values": {
        "isSecondInningsStarted": "false",
        "t1RR": "--.--",
        "t1Code": "HHP",
        "batsman2LastName": "D",
        "lastOutRuns": "",
        "RRR": "0.05",
        "batsman1Name": "Goutham R",
        "batsman2Runs": "0",
        "manOfTheMatchNickName": "",
        "projectedRunRate": [],
        "seriesName": "2024-Winter-TapedBall-DivB",
        "lastOutString": "",
        "totalOvers": 20,
        "batsman2OutString": "<span>not out</span>",
        "lastOUtSixers": "",
        "toss": "Hutto Hippos WON THE TOSS AND ELECTED TO BAT",
        "t1ID": 566,
        "remainingOvers": "20.0",
        "shortResult": "HHP 0/0 (0.0/20 ov) ",
        "batsman1OutString": "<span>not out</span>",
        "rrOrRPB": "RR ",
        "tossWon": "HHP",
        "t2Name": "Invaders",
        "lastOutProfileImange": "",
        "bowlerFirstName": "",
        "batsman2Balls": "0",
        "lastOutFours": "",
        "bowlerProfileImange": "/documentsRep/profilePics/no_image.png",
        "batsman2IsOut": "0",
        "batsman2NickName": "",
        "bowlerWickets": "0",
        "overs": "0.0",
        "lastOutBalls": "",
        "batsman2Fours": "0",
        "result": "Hutto Hippos: 0/0 (0.0/20 OVERS ) ",
        "bowlerID": 0,
        "batsman1LastName": "Reddy",
        "revisedOvers": 0,
        "bowlerName": "",
        "displayNickNameOnOverlay": false,
        "t1Overs": "0.0",
        "dots": 0,
        "batsman2ProfileImange": "/documentsRep/profilePics/8ddae24a-48a6-4dbb-a251-ac5952cf72f5.jpeg",
        "requiredRuns": "1",
        "bowlerOvers": "0.0",
        "parScore": "0",
        "careerProfileImage": "",
        "revisedTarget": 0,
        "oversOrBalls": "OVERS ",
        "secondLogo": "/utilsv2/img/icons/no-image-team4.jpg",
        "momImagePath": "",
        "careerPlayerName": "",
        "t1Wickets": "0",
        "t2Wickets": "0",
        "isSuperOver": "false",
        "showScoreMsgForOpositTeam": "<span class='numberColorClass'>HHP</span> vs <span class='numberColorClass'>INV</span> ",
        "batsman2FirstName": "Vijay",
        "batsman1NickName": "Goutham",
        "groundName": "LPCL-G3",
        "tWickets": "0",
        "firstLogo": "/documentsRep/teamLogos/ff4a00a1-f90d-4baa-b8bf-5135d0e84c4e.jpg",
        "teamID": 0,
        "isMatchEnded": "0",
        "t2Code": "INV",
        "runrate": "--.--",
        "isDls": false,
        "isSuperOverSecondInningsStarted": "false",
        "t1Name": "Hutto Hippos",
        "batsman2Name": "Vijay D",
        "batsman1Runs": "0",
        "bowlerRuns": "0",
        "batsman2Sixers": "0",
        "bowlerMaidens": "0",
        "t2Overs": "0.0",
        "lastOutIsOut": "",
        "batsman2ID": 2598788,
        "manOfTheMatch": "",
        "t1Total": "0",
        "lastOutFirstName": "",
        "t2RR": "--.--",
        "lastOutLastName": "",
        "fow": "",
        "lastOutName": "",
        "batsman1Sixers": "0",
        "batsman1Balls": "0",
        "batsman1Fours": "0",
        "matchId": "1928",
        "t2Total": "0",
        "batsman1FirstName": "Goutham",
        "currentPartnershipMap": {
            "partnershipBatsman2ContributionRuns": "0",
            "partnershipTotalRuns": "0",
            "partnershipTeamID": "566",
            "partnershipBatsman1ProfilePic": "/documentsRep/profilePics/no_image.png",
            "partnershipBatsman2ContributionBalls": "0",
            "partnershipBatsman1ID": "3061960",
            "partnershipBatsman1TotalRuns": "0",
            "partnershipBatsman2LastName": "D",
            "partnershipBatsman2ID": "2598788",
            "batsman1DisplayName": "Goutham",
            "partnershipBatsman1ContributionBalls": "0",
            "partnershipBatsman1FirstName": "Goutham",
            "partnershipBatsman1Name": "Goutham R",
            "partnershipBatsman1LastName": "Reddy",
            "partnershipBatsman1Balls": "0",
            "partnershipBatsman2TotalRuns": "0",
            "partnershipTotalBalls": "0",
            "partnershipBatsman1ContributionRuns": "0",
            "partnershipBatsman2Name": "Vijay D",
            "partnershipBatsman2ProfilePic": "/documentsRep/profilePics/8ddae24a-48a6-4dbb-a251-ac5952cf72f5.jpeg",
            "partnershipBatsman2FirstName": "Vijay",
            "partnershipBatsman2Balls": "0",
            "batsman2DisplayName": ""
        },
        "t2ID": 567,
        "lastOutID": 0,
        "batsman1ProfileImange": "/documentsRep/profilePics/no_image.png",
        "tTotal": "0",
        "batsman1ID": 3061960,
        "batsman1IsOut": "0",
        "isTestOr2x": false,
        "liveYouTubeLink": "//www.youtube.com/embed/iVZJiaFZrQM?rel=0&autoplay=1"
    },
    "isSecondInningsStarted": false,
    "isSuperOver": false,
    "isSuperOverSecondInningsStarted": false,
    "balls": ["1", "4", ".", "W", "6", "1"],
    "is2XCricket": false,
    "sponsorsImgPaths": [],
    "isAutoSwitchEnabled": 0
}

export const mock_1stInnings = {
    "view": 1,
    "values": {
        "isSecondInningsStarted": "false",
        "t1RR": "14.00",
        "t1Code": "STG",
        "batsman2LastName": "Akula",
        "lastOutRuns": "44",
        "RRR": "3.55",
        "batsman1Name": "Abhinav V",
        "batsman2Runs": "7",
        "manOfTheMatchNickName": "",
        "projectedRunRate": [],
        "seriesName": "2024-Fall-Champions",
        "lastOutString": "<span>b </span><span class='outname'>Abhinandan reddy K</span>",
        "totalOvers": 20,
        "batsman2OutString": "<span>not out</span>",
        "lastOUtSixers": "3",
        "toss": "Stags WON THE TOSS AND ELECTED TO BAT",
        "t1ID": 491,
        "remainingOvers": "20.0",
        "shortResult": "STG 70/1 (5.0/20 ov) ",
        "batsman1OutString": "<span>not out</span>",
        "rrOrRPB": "RR ",
        "tossWon": "STG",
        "t2Name": "Ground Breakers",
        "lastOutProfileImange": "/documentsRep/profilePics/627d5061-89e2-4205-baac-647648cbba5a.jpeg",
        "bowlerFirstName": "Chandu Bhargav",
        "batsman2Balls": "3",
        "lastOutFours": "4",
        "bowlerProfileImange": "/documentsRep/profilePics/302247fb-ce67-4009-a6a0-d6eb50b2206a.jpeg",
        "batsman2IsOut": "0",
        "batsman2NickName": "",
        "bowlerWickets": "0",
        "overs": "5.0",
        "lastOutBalls": "18",
        "batsman2Fours": "1",
        "result": "Stags: 70/1 (5.5/20 OVERS )  ",
        "bowlerID": 2891590,
        "batsman1LastName": "Manthri",
        "revisedOvers": 0,
        "bowlerName": "Chandu Bhargav K",
        "displayNickNameOnOverlay": false,
        "t1Overs": "5.0",
        "bowlerLastName": "Kasukurthi",
        "dots": 0,
        "batsman2ProfileImange": "/documentsRep/profilePics/54d79bb9-16bb-4216-bccc-7607edebee49.jpeg",
        "requiredRuns": "71",
        "bowlerOvers": "0.0",
        "parScore": "0",
        "careerProfileImage": "",
        "revisedTarget": 0,
        "oversOrBalls": "OVERS ",
        "secondLogo": "/documentsRep/teamLogos/62644c30-9f3e-4124-8fc6-6d92964ae6cd.jpg",
        "momImagePath": "",
        "careerPlayerName": "",
        "t1Wickets": "1",
        "t2Wickets": "0",
        "isSuperOver": "false",
        "showScoreMsgForOpositTeam": "<span class='numberColorClass'>STG</span>  vs <span class='numberColorClass'>GBR</span> ",
        "bowlerNickName": "chandu",
        "batsman2FirstName": "Ravi",
        "batsman1NickName": "",
        "groundName": "LPCL-G7",
        "tWickets": "1",
        "firstLogo": "/documentsRep/teamLogos/f49c9ea9-1d4c-4a32-a8e5-b4a228ba61df.jpg",
        "teamID": 0,
        "isMatchEnded": "0",
        "t2Code": "GBR",
        "runrate": "14.00",
        "isDls": false,
        "isSuperOverSecondInningsStarted": "false",
        "t1Name": "TOPGUNS UNITED",
        "batsman2Name": "Ravi A",
        "batsman1Runs": "43",
        "bowlerRuns": "0",
        "batsman2Sixers": "0",
        "bowlerMaidens": "0",
        "t2Overs": "0.0",
        "lastOutIsOut": "1",
        "batsman2ID": 1789247,
        "manOfTheMatch": "",
        "t1Total": "70",
        "lastOutFirstName": "Manideep",
        "t2RR": "--.--",
        "lastOutLastName": "Mandy",
        "fow": "",
        "lastOutName": "Manideep M",
        "batsman1Sixers": "0",
        "batsman1Balls": "10",
        "batsman1Fours": "2",
        "matchId": "1939",
        "t2Total": "0",
        "batsman1FirstName": "Sreekanth",
        "currentPartnershipMap": {
            "partnershipBatsman2ContributionRuns": "7",
            "partnershipTotalRuns": "10",
            "partnershipTeamID": "491",
            "partnershipBatsman1ProfilePic": "/documentsRep/profilePics/74c021e1-332a-4b08-a510-0dc57647454c.jpeg",
            "partnershipBatsman2ContributionBalls": "3",
            "partnershipBatsman1ID": "645263",
            "partnershipBatsman1TotalRuns": "13",
            "partnershipBatsman2LastName": "Akula",
            "partnershipBatsman2ID": "1789247",
            "batsman1DisplayName": "",
            "partnershipBatsman1ContributionBalls": "4",
            "partnershipBatsman1FirstName": "Sreekanth",
            "partnershipBatsman1Name": "Sreekanth M",
            "partnershipBatsman1LastName": "Manthri",
            "partnershipBatsman1Balls": "10",
            "partnershipBatsman2TotalRuns": "7",
            "partnershipTotalBalls": "7",
            "partnershipBatsman1ContributionRuns": "2",
            "partnershipBatsman2Name": "Ravi A",
            "partnershipBatsman2ProfilePic": "/documentsRep/profilePics/54d79bb9-16bb-4216-bccc-7607edebee49.jpeg",
            "partnershipBatsman2FirstName": "Ravi",
            "partnershipBatsman2Balls": "3",
            "batsman2DisplayName": ""
        },
        "t2ID": 485,
        "lastOutID": 2042729,
        "batsman1ProfileImange": "/documentsRep/profilePics/74c021e1-332a-4b08-a510-0dc57647454c.jpeg",
        "tTotal": "70",
        "batsman1ID": 645263,
        "batsman1IsOut": "0",
        "isTestOr2x": false,
        "liveYouTubeLink": "//www.youtube.com/embed/iVZJiaFZrQM?rel=0&autoplay=1"
    },
    "isSecondInningsStarted": false,
    "isSuperOver": false,
    "isSuperOverSecondInningsStarted": false,
    "balls": [],
    "is2XCricket": false,
    "sponsorsImgPaths": [],
    "isAutoSwitchEnabled": 0
}

export const mock_2ndInnings = {
    "view": 1,
    "values": {
        "isSecondInningsStarted": "true",
        "t1RR": "7.10",
        "showMsgForScoreNeeded": "<span>Invaders </span><span class='numberColorClass'>NEED</span> 143 <span class='numberColorClass'>FROM</span> 20.0 <span class='numberColorClass'>OVERS </span> 7.15 <span class='numberColorClass'>RRR</span>",
        "t1Code": "HHP",
        "batsman2LastName": "G",
        "lastOutRuns": "11",
        "RRR": "7.15",
        "batsman1Name": "Vijaykumar V",
        "batsman2Runs": "0",
        "manOfTheMatchNickName": "",
        "projectedRunRate": [],
        "seriesName": "2024-Winter-TapedBall-DivB",
        "lastOutString": "<span>b </span><span class='outname'>Siva Krishna V</span>",
        "totalOvers": 20,
        "batsman2OutString": "<span>not out</span>",
        "lastOUtSixers": "0",
        "toss": "Hutto Hippos WON THE TOSS AND ELECTED TO BAT",
        "t1ID": 566,
        "remainingOvers": "20.0",
        "shortResult": "HHP 142/8 (20.0/20 ov) ",
        "batsman1OutString": "<span>not out</span>",
        "rrOrRPB": "RR ",
        "tossWon": "HHP",
        "t2Name": "Invaders",
        "lastOutProfileImange": "/documentsRep/profilePics/f88cd3e4-d3f3-4c44-a52d-8df43cd74db6.jpeg",
        "bowlerFirstName": "",
        "batsman2Balls": "0",
        "lastOutFours": "0",
        "bowlerProfileImange": "/documentsRep/profilePics/no_image.png",
        "batsman2IsOut": "0",
        "batsman2NickName": "",
        "bowlerWickets": "0",
        "overs": "0.0",
        "lastOutBalls": "8",
        "batsman2Fours": "0",
        "result": "Hutto Hippos: 142/8 (20.0/20 OVERS )  ",
        "bowlerID": 0,
        "batsman1LastName": "Valipireddy",
        "revisedOvers": 0,
        "bowlerName": "",
        "displayNickNameOnOverlay": false,
        "t1Overs": "20.0",
        "dots": 0,
        "batsman2ProfileImange": "/documentsRep/profilePics/dded800c-4b44-4a2e-9903-fa07f6fd13b2.jpeg",
        "requiredRuns": "143",
        "bowlerOvers": "0.0",
        "parScore": "0",
        "careerProfileImage": "",
        "revisedTarget": 0,
        "oversOrBalls": "OVERS ",
        "secondLogo": "/documentsRep/teamLogos/ff4a00a1-f90d-4baa-b8bf-5135d0e84c4e.jpg",
        "momImagePath": "",
        "careerPlayerName": "",
        "t1Wickets": "8",
        "t2Wickets": "0",
        "isSuperOver": "false",
        "showScoreMsgForOpositTeam": "<span class='numberColorClass'>HHP</span>  142/8<span class='numberColorClass'> OVERS </span> 20.0",
        "batsman2FirstName": "Nayan",
        "batsman1NickName": "",
        "groundName": "LPCL-G3",
        "tWickets": "0",
        "firstLogo": "/utilsv2/img/icons/no-image-team1.jpg",
        "teamID": 0,
        "isMatchEnded": "0",
        "t2Code": "INV",
        "runrate": "--.--",
        "isDls": false,
        "isSuperOverSecondInningsStarted": "false",
        "t1Name": "Hutto Hippos",
        "batsman2Name": "Nayan G",
        "batsman1Runs": "0",
        "bowlerRuns": "0",
        "batsman2Sixers": "0",
        "bowlerMaidens": "0",
        "t2Overs": "0.0",
        "lastOutIsOut": "1",
        "batsman2ID": 2794310,
        "manOfTheMatch": "",
        "t1Total": "142",
        "lastOutFirstName": "Vikas",
        "t2RR": "--.--",
        "lastOutLastName": "babu",
        "fow": "",
        "lastOutName": "Vikas b",
        "batsman1Sixers": "0",
        "batsman1Balls": "0",
        "batsman1Fours": "0",
        "matchId": "1928",
        "t2Total": "0",
        "batsman1FirstName": "Vijaykumar",
        "currentPartnershipMap": {
            "partnershipBatsman2ContributionRuns": "0",
            "partnershipTotalRuns": "0",
            "partnershipTeamID": "567",
            "partnershipBatsman1ProfilePic": "/documentsRep/profilePics/9625b7ec-e8b2-4def-8b43-5ffc4ea8825e.png",
            "partnershipBatsman2ContributionBalls": "0",
            "partnershipBatsman1ID": "580489",
            "partnershipBatsman1TotalRuns": "0",
            "partnershipBatsman2LastName": "G",
            "partnershipBatsman2ID": "2794310",
            "batsman1DisplayName": "",
            "partnershipBatsman1ContributionBalls": "0",
            "partnershipBatsman1FirstName": "Vijaykumar",
            "partnershipBatsman1Name": "Vijaykumar V",
            "partnershipBatsman1LastName": "Valipireddy",
            "partnershipBatsman1Balls": "0",
            "partnershipBatsman2TotalRuns": "0",
            "partnershipTotalBalls": "0",
            "partnershipBatsman1ContributionRuns": "0",
            "partnershipBatsman2Name": "Nayan G",
            "partnershipBatsman2ProfilePic": "/documentsRep/profilePics/dded800c-4b44-4a2e-9903-fa07f6fd13b2.jpeg",
            "partnershipBatsman2FirstName": "Nayan",
            "partnershipBatsman2Balls": "0",
            "batsman2DisplayName": ""
        },
        "t2ID": 567,
        "lastOutID": 2186754,
        "batsman1ProfileImange": "/documentsRep/profilePics/9625b7ec-e8b2-4def-8b43-5ffc4ea8825e.png",
        "tTotal": "0",
        "batsman1ID": 580489,
        "batsman1IsOut": "0",
        "isTestOr2x": false,
        "liveYouTubeLink": "//www.youtube.com/embed/iVZJiaFZrQM?rel=0&autoplay=1"
    },
    "isSecondInningsStarted": true,
    "isSuperOver": false,
    "isSuperOverSecondInningsStarted": false,
    "balls": ["6", "6", "4", "1", "W", "."],
    "is2XCricket": false,
    "sponsorsImgPaths": [],
    "isAutoSwitchEnabled": 0
}

export const mock_matchEnded = {
    "view": 1,
    "values": {
        "isSecondInningsStarted": "true",
        "t1RR": "7.84",
        "showMsgForScoreNeeded": "",
        "t1Code": "GRY",
        "batsman2LastName": "Padimalla",
        "lastOutRuns": "2",
        "RRR": "0.00",
        "batsman1Name": "",
        "batsman2Runs": "6",
        "manOfTheMatchNickName": "",
        "projectedRunRate": [],
        "seriesName": "2024-Fall-Champions",
        "lastOutString": "<span>c </span><span class='outname'>Vamsee Krishna K</span><span> b </span><span class='outname'>Srini V</span>",
        "totalOvers": 20,
        "batsman2OutString": "<span>not out</span>",
        "lastOUtSixers": "0",
        "toss": "TOPGUNS UNITED WON THE TOSS AND ELECTED TO BOWL",
        "t1ID": 484,
        "remainingOvers": "4.0",
        "shortResult": "TGN won by 5 Wickets",
        "batsman1OutString": "<span>not out</span>",
        "rrOrRPB": "RR ",
        "tossWon": "TGN",
        "t2Name": "TOPGUNS UNITED",
        "lastOutProfileImange": "/documentsRep/profilePics/e8a6015e-ad61-4e58-bd77-3d89cada6e6f.jpg",
        "bowlerFirstName": "Ranjeet",
        "batsman2Balls": "3",
        "lastOutFours": "0",
        "bowlerProfileImange": "/documentsRep/profilePics/862c2d42-c42c-4b0c-8b66-40f95a5b629e.png",
        "batsman2IsOut": "0",
        "batsman2NickName": "Mahee",
        "bowlerWickets": "2",
        "overs": "16.0",
        "lastOutBalls": "2",
        "batsman2Fours": "1",
        "result": "TOPGUNS UNITED won by 5 Wickets",
        "bowlerID": 2886512,
        "revisedOvers": 0,
        "bowlerName": "Ranjeet P",
        "displayNickNameOnOverlay": false,
        "t1Overs": "20.0",
        "bowlerLastName": "Patil",
        "dots": 3,
        "batsman2ProfileImange": "/documentsRep/profilePics/b54da520-8c2b-4296-9f1b-12900142c839.jpeg",
        "requiredRuns": "0",
        "bowlerOvers": "3.0",
        "parScore": "121",
        "careerProfileImage": "",
        "revisedTarget": 0,
        "oversOrBalls": "OVERS ",
        "secondLogo": "/documentsRep/teamLogos/2b055ae5-d4aa-43fa-9cc7-c0a17db76c1c.jpg",
        "momImagePath": "/documentsRep/profilePics/b123a332-38ff-445e-a9c9-50a4c57fb69e.jpeg",
        "careerPlayerName": "",
        "t1Wickets": "5",
        "t2Wickets": "5",
        "isSuperOver": "false",
        "showScoreMsgForOpositTeam": "<span class='numberColorClass'>GRY</span>  157/5<span class='numberColorClass'> OVERS </span> 20.0",
        "bowlerNickName": "Abhi",
        "batsman2FirstName": "Mahesh",
        "groundName": "LPCL-G8",
        "tWickets": "5",
        "firstLogo": "/documentsRep/teamLogos/6afd1032-836c-49ac-9462-c0d1b4d66b99.jpeg",
        "teamID": 0,
        "isMatchEnded": "1",
        "t2Code": "TGN",
        "runrate": "9.88",
        "isDls": false,
        "isSuperOverSecondInningsStarted": "false",
        "t1Name": "Greyhounds",
        "batsman2Name": "Mahesh P",
        "batsman1Runs": "1",
        "bowlerRuns": "21",
        "batsman2Sixers": "0",
        "bowlerMaidens": "0",
        "t2Overs": "16.0",
        "lastOutIsOut": "1",
        "batsman2ID": 4629151,
        "manOfTheMatch": "Rakesh Gopishetty",
        "customTextValue": "hghjkghjk",
        "t1Total": "157",
        "lastOutFirstName": "Nandan",
        "t2RR": "9.88",
        "lastOutLastName": "Patibandla",
        "fow": "",
        "lastOutName": "Nandan P",
        "batsman1Sixers": "0",
        "batsman1Balls": "1",
        "batsman1Fours": "0",
        "matchId": "1853",
        "t2Total": "158",
        "batsman1FirstName": "",
        "currentPartnershipMap": {
            "partnershipBatsman2ContributionRuns": "0",
            "partnershipTotalRuns": "2",
            "partnershipTeamID": "493",
            "partnershipBatsman1ProfilePic": "/documentsRep/profilePics/no_image.png",
            "partnershipBatsman2ContributionBalls": "0",
            "partnershipBatsman1ID": "4086187",
            "partnershipBatsman1TotalRuns": "1",
            "partnershipBatsman2LastName": "Padimalla",
            "partnershipBatsman2ID": "4629151",
            "partnershipBatsman1ContributionBalls": "1",
            "partnershipBatsman1FirstName": "",
            "partnershipBatsman1Name": "",
            "partnershipBatsman1Balls": "1",
            "partnershipBatsman2TotalRuns": "6",
            "partnershipTotalBalls": "1",
            "partnershipBatsman1ContributionRuns": "1",
            "partnershipBatsman2Name": "Mahesh P",
            "partnershipBatsman2ProfilePic": "/documentsRep/profilePics/b54da520-8c2b-4296-9f1b-12900142c839.jpeg",
            "partnershipBatsman2FirstName": "Mahesh",
            "partnershipBatsman2Balls": "3",
            "batsman2DisplayName": "Mahee"
        },
        "t2ID": 493,
        "lastOutID": 767514,
        "batsman1ProfileImange": "/documentsRep/profilePics/no_image.png",
        "tTotal": "158",
        "batsman1ID": 4086187,
        "batsman1IsOut": "0",
        "isTestOr2x": false,
        "liveYouTubeLink": "//www.youtube.com/embed/ERtJGMa-uoU?rel=0&autoplay=1&mute=1"
    },
    "isSecondInningsStarted": true,
    "isSuperOver": false,
    "isSuperOverSecondInningsStarted": false,
    "balls": [
        "1wd"
    ],
    "is2XCricket": false,
    "sponsorsImgPaths": [],
    "isAutoSwitchEnabled": 0
}

export const mock_noTeamImage = {
    "view": 1,
    "values": {
        "isSecondInningsStarted": "true",
        "t1RR": "4.34",
        "showMsgForScoreNeeded": "",
        "t1Code": "ASH",
        "batsman2LastName": "Palepu",
        "lastOutRuns": "28",
        "RRR": "--.--",
        "batsman1Name": "anuj u",
        "batsman2Runs": "7",
        "manOfTheMatchNickName": "",
        "projectedRunRate": [

        ],
        "seriesName": "FireWater 2025 Fall Tape -Div-D",
        "lastOutString": "\u003cspan\u003eb \u003c/span\u003e\u003cspan class\u003d\u0027outname\u0027\u003eMahesh G\u003c/span\u003e",
        "totalOvers": 20,
        "batsman2OutString": "\u003cspan\u003enot out\u003c/span\u003e",
        "lastOUtSixers": "0",
        "toss": "Austin Shaqs WON THE TOSS AND ELECTED TO BAT",
        "t1ID": 893,
        "remainingOvers": "11.1",
        "shortResult": "TTR won by 8 Wickets",
        "batsman1OutString": "\u003cspan\u003enot out\u003c/span\u003e",
        "rrOrRPB": "RR ",
        "tossWon": "ASH",
        "t2Name": "Travisso Titans",
        "lastOutProfileImange": "/documentsRep/profilePics/a2098993-d32b-42b2-a6c3-e1ca2f521438.jpeg",
        "bowlerFirstName": "Laxman",
        "batsman2Balls": "7",
        "lastOutFours": "3",
        "bowlerProfileImange": "/documentsRep/profilePics/default_male_profilePic.png",
        "batsman2IsOut": "0",
        "batsman2NickName": "",
        "bowlerWickets": "0",
        "overs": "8.5",
        "lastOutBalls": "23",
        "batsman2Fours": "1",
        "result": "Travisso Titans won by 8 Wickets",
        "bowlerID": 5144350,
        "batsman1LastName": "upadhyay",
        "revisedOvers": 0.0,
        "bowlerName": "Laxman R",
        "displayNickNameOnOverlay": false,
        "t1Overs": "17.3",
        "bowlerLastName": "Reddy",
        "dots": 3,
        "batsman2ProfileImange": "/documentsRep/profilePics/b3c73728-ca8d-4225-a4fa-414f4c19a7b6.jpeg",
        "requiredRuns": "-2",
        "bowlerOvers": "0.5",
        "parScore": "30",
        "careerProfileImage": "",
        "revisedTarget": 0,
        "oversOrBalls": "OVERS ",
        "secondLogo": "/documentsRep/teamLogos/0409175c-301c-4b91-b1ef-6e0f47b7df8c.jpg",
        "momImagePath": "/documentsRep/profilePics/no_image.png",
        "careerPlayerName": "",
        "t1Wickets": "10",
        "t2Wickets": "2",
        "isSuperOver": "false",
        "showScoreMsgForOpositTeam": "\u003cspan class\u003d\u0027numberColorClass\u0027\u003eASH\u003c/span\u003e  76/10\u003cspan class\u003d\u0027numberColorClass\u0027\u003e OVERS \u003c/span\u003e 17.3",
        "bowlerNickName": "",
        "batsman2FirstName": "Sravanth",
        "batsman1NickName": "",
        "groundName": "LPCL-G4",
        "tWickets": "2",
        "firstLogo": "https://static.cricclubs.com/utilsv2/img/icons/no-image-team3.jpg",
        "teamID": 0,
        "isMatchEnded": "1",
        "t2Code": "TTR",
        "runrate": "8.94",
        "isDls": false,
        "isSuperOverSecondInningsStarted": "false",
        "t1Name": "Austin Shaqs",
        "batsman2Name": "Sravanth P",
        "batsman1Runs": "4",
        "bowlerRuns": "6",
        "batsman2Sixers": "0",
        "bowlerMaidens": "0",
        "t2Overs": "8.5",
        "lastOutIsOut": "1",
        "batsman2ID": 4669770,
        "manOfTheMatch": "Anup Dugar",
        "t1Total": "76",
        "lastOutFirstName": "Sreedhar",
        "t2RR": "8.94",
        "lastOutLastName": "Vasepalli",
        "fow": "",
        "lastOutName": "Sreedhar V",
        "batsman1Sixers": "0",
        "batsman1Balls": "3",
        "batsman1Fours": "1",
        "matchId": "3250",
        "t2Total": "79",
        "batsman1FirstName": "anuj",
        "currentPartnershipMap": {
            "partnershipBatsman2ContributionRuns": "1",
            "partnershipTotalRuns": "6",
            "partnershipTeamID": "905",
            "partnershipBatsman1ProfilePic": "/documentsRep/profilePics/default_male_profilePic.png",
            "partnershipBatsman2ContributionBalls": "2",
            "partnershipBatsman1ID": "4383388",
            "partnershipBatsman1TotalRuns": "4",
            "partnershipBatsman2LastName": "Palepu",
            "partnershipBatsman2ID": "4669770",
            "batsman1DisplayName": "",
            "partnershipBatsman1ContributionBalls": "3",
            "partnershipBatsman1FirstName": "anuj",
            "partnershipBatsman1Name": "anuj u",
            "partnershipBatsman1LastName": "upadhyay",
            "partnershipBatsman1Balls": "3",
            "partnershipBatsman2TotalRuns": "7",
            "partnershipTotalBalls": "5",
            "partnershipBatsman1ContributionRuns": "4",
            "partnershipBatsman2Name": "Sravanth P",
            "partnershipBatsman2ProfilePic": "/documentsRep/profilePics/b3c73728-ca8d-4225-a4fa-414f4c19a7b6.jpeg",
            "partnershipBatsman2FirstName": "Sravanth",
            "partnershipBatsman2Balls": "7",
            "batsman2DisplayName": ""
        },
        "t2ID": 905,
        "lastOutID": 2795747,
        "batsman1ProfileImange": "/documentsRep/profilePics/default_male_profilePic.png",
        "tTotal": "79",
        "batsman1ID": 4383388,
        "batsman1IsOut": "0",
        "isTestOr2x": false,
        "liveYouTubeLink": "//www.youtube.com/embed/iVZJiaFZrQM?rel\u003d0\u0026autoplay\u003d1"
    },
    "isSecondInningsStarted": true,
    "isSuperOver": false,
    "isSuperOverSecondInningsStarted": false,
    "balls": [
        ".",
        "1",
        ".",
        ".",
        "1wd",
        "4"
    ],
    "is2XCricket": false,
    "sponsorsImgPaths": [

    ],
    "isAutoSwitchEnabled": 0
}